### ISSUE TITLE
Unity versions of Final Doom overwrite widescreen status bar

### ISSUE THREAD

**Issue by Zoltar007** [Owlet7/wadfusion#16]
~~Release [WadFusion 1.0.1](https://github.com/Owlet7/wadfusion/releases/tag/v1.0.1) mentions, "Enabled Remix soundtrack in TNT Evilution", however the remix soundtrack doesn't play during any map in that episode. No errors are displayed in the console, nor are there any errors in the wadfusion.log file. I've confirmed that this is broken in the 1.0.1, 1.1.0 & 1.1.1 releases &~~ all WAD files have been obtained from the Steam releases, with the exception of SIGIL & SIGIL II from Romero's store.

"wadfusion.log" log file on [Pastebin](https://pastebin.com/Zs1xyjU5).

I'm not sure if this is also a bug, but the Unity port status bar isn't included unless all of the following WAD files are present (both unity & kex):
doomunity, doom2unity, tntunity, plutoniaunity, doomkex, doom2kex, tntkex, plutoniakex

**Comment by Owlet7** [comment]
Are you sure you have "Andrew Hulshult's IDKFA soundtrack" enabled in WadFusion Options, and have tried warping to one of the maps where the original Doom or Doom 2 music is used (e.g. `TN_MAP21`)?

I would prefer if separate issues are opened per, uh, issue, but I will address the part about the Unity statusbar. It is caused by the Unity versions of the Final Doom wads not having a widescreen statusbar, only the KEX versions do.

Note that the Unity and KEX ports now have different statusbars -- Unity's is aimed at 16:9 support, KEX's also supports 21:9.

**Comment by Zoltar007** [comment]
Sorry for the delay. I had a long work day, so I've only been able to reply now.

I wasn't aware that TNT: Evilution only had certain maps play the IDKFA soundtrack. I've confirmed that `TN_MAP21` & even `TN_MAP03` do play music from the soundtrack correctly. Sorry for the confusion on my part.

Regarding the statusbar, this was showing the default doom statusbar for all episodes at 16:9 (excluding the two Legacy Of Rust episodes), until I included the `doomkex`, `doom2kex`, `tntkex` & `plutoniakex` WADs. For example:

Knee-Deep In The Dead:
![Screenshot_Doom_20241010_033416](https://github.com/user-attachments/assets/034fb21a-8531-45fd-8730-e1856e545698)

Hell On Earth:
![Screenshot_Doom_20241010_033444](https://github.com/user-attachments/assets/73716fb6-a583-4830-ab1e-7b3ba5498d03)

Linked on PasteBin is the [wadfusion.log](https://pastebin.com/hm6N0dPa) file, excluding the 4 above mentioned *kex WADs.

**Comment by Owlet7** [comment]
It was an oversight on my end. The script extracted the same widescreen resources from both the Unity wads and the KEX wads. 

In 1.1.0, I made it so that the script would also extract the widescreen statusbar from Final Doom, in cases where the user used only them to generate doom_complete.pk3, without Doom 1 or Doom 2 (a weird use case, but I'm not judging).

The issue is that I forgot that the Unity versions didn't have widescreen statusbars in Final Doom, so they'd get overwritten with vanilla 4:3 ones. I corrected this in the current version of the script, which now uses a separate list for KEX widescreen resources in Final Doom.

Unity and KEX wads shouldn't be used both at the same time, as the script will overwrite anything that it extracts from the Unity wads with the same resources from the KEX wads, so it's redundant. If you have access to both, use the KEX wads, unless you have a specific reason not to.

Regarding the IDKFA music in TNT, yeah, they only made covers for the Doom 1 and Doom 2 music. The original tracks in TNT and LoR are MIDI-only.

If you have Python 3 installed, you could run the latest development version of WadFusion by downloading the [source code](https://github.com/Owlet7/wadfusion/archive/refs/heads/master.zip).

**Comment by Owlet7** [comment]
Update your copy of DOOM + DOOM II on Steam or GOG, use the new WADs. Open a separate issue next time.

**Comment by Zoltar007** [comment]
I've confirmed that the latest development version resolves this bug.
I agree that using the KEX WADs over the Unity WADs is the best way forward.
I'm happy for this issue to be closed.

**Comment by Owlet7** [comment]
Thanks for confirming!
