### ISSUE TITLE
Program still generates "doom_complete.pk3"

### ISSUE THREAD

**Issue by klearscreen** [Owlet7/wadfusion#22]
The readme mentions "doom_fusion.ipk3", but the file generated is still "doom_complete.pk3".

**Comment by domyoji81** [comment]
You're likely running the 1.1.1 release, which is outdated. If you have python installed you can download the latest code and run the wadfusion.py script to fuse your wads with all the latest commits, which includes the switch to doom_fusion.pk3. Otherwise you'll need to wait until Owlet7 pushes another release.

![code](https://github.com/user-attachments/assets/c20a025a-f61e-419c-9766-bad904d1250c)

**Comment by JimFlasch** [comment]
Followed your instructions above and did not get a doom_fusion.ipk3 file, only a temp folder with seven folders of extracted data and two empty folders, mapinfo and zscript.

**Comment by klearscreen** [comment]
If you're using the " wadfusion_win.zip" from the release 1.1.1, it creates a file called "doom_complete.pk3".

**Comment by JimFlasch** [comment]
Don't have that either.

**Comment by Owlet7** [comment]
@JimFlasch Could you please post the log file?

**Comment by JimFlasch** [comment]
Here it is.
[wadfusion.log](https://github.com/user-attachments/files/17443770/wadfusion.log)

**Comment by Owlet7** [comment]
I'm unable to replicate your crash. Have you used a previous version of WF, and if yes, did you extract the dev build into a new, separate folder?

**Comment by Owlet7** [comment]
Issue is no longer relevant now with the new release.

@JimFlasch If the script is still crashing for you, please open a new issue.
